//todo: remove mock functionality - this is temporary data for the design prototype
import { Sofa } from "@shared/schema";
import sofaImage1 from "@assets/generated_images/beige_modern_fixed_sofa.png";
import sofaImage2 from "@assets/generated_images/gray_convertible_sofa_bed.png";
import sofaImage3 from "@assets/generated_images/brown_leather_modern_armchair.png";
import sofaImage4 from "@assets/generated_images/pink_meridienne_chaise_lounge.png";
import sofaImage5 from "@assets/generated_images/charcoal_sectional_lounge_sofa.png";
import sofaImage6 from "@assets/generated_images/navy_blue_velvet_loveseat.png";

export const mockSofas: Sofa[] = [
  {
    id: "1",
    name: "Oslo Comfort",
    type: "fixe",
    width: 178,
    depth: 88,
    height: 82,
    price: "1299.00",
    comfort: "Confort ferme, assise haute",
    inStore: true,
    inStock: true,
    onOrder: false,
    mainImage: sofaImage1,
    images: [sofaImage1],
    description: "Canapé fixe au design scandinave épuré, parfait pour les espaces contemporains.",
    features: ["Tissu anti-taches", "Pieds en chêne massif", "Coussins déhoussables"],
  },
  {
    id: "2",
    name: "Milano Convertible",
    type: "convertible",
    width: 200,
    depth: 95,
    height: 85,
    price: "1899.00",
    comfort: "Confort moelleux, convertible express",
    inStore: false,
    inStock: true,
    onOrder: false,
    mainImage: sofaImage2,
    images: [sofaImage2],
    description: "Canapé convertible haut de gamme avec système de couchage quotidien.",
    features: ["Matelas 14cm inclus", "Mécanisme rapido", "Coffre de rangement"],
  },
  {
    id: "3",
    name: "Churchill Classic",
    type: "fauteuil",
    width: 95,
    depth: 92,
    height: 98,
    price: "899.00",
    comfort: "Confort d'exception, cuir pleine fleur",
    inStore: true,
    inStock: false,
    onOrder: true,
    mainImage: sofaImage3,
    images: [sofaImage3],
    description: "Fauteuil en cuir véritable, inspiré du design anglais classique.",
    features: ["Cuir aniline", "Structure hêtre massif", "Dossier ergonomique"],
  },
  {
    id: "4",
    name: "Élégance Méridienne",
    type: "meridienne",
    width: 165,
    depth: 75,
    height: 78,
    price: "1499.00",
    comfort: "Confort raffiné, assise profonde",
    inStore: false,
    inStock: false,
    onOrder: true,
    mainImage: sofaImage4,
    images: [sofaImage4],
    description: "Méridienne au design élégant, idéale pour créer un coin lecture.",
    features: ["Velours haute qualité", "Pieds laiton brossé", "Accoudoir asymétrique"],
  },
  {
    id: "5",
    name: "Urban Lounge",
    type: "fixe",
    width: 280,
    depth: 105,
    height: 75,
    price: "2499.00",
    comfort: "Confort lounge, assise extra profonde",
    inStore: true,
    inStock: true,
    onOrder: false,
    mainImage: sofaImage5,
    images: [sofaImage5],
    description: "Grand canapé d'angle au confort exceptionnel pour une détente maximale.",
    features: ["Configuration modulable", "Têtières réglables", "Assise ultra-profonde"],
  },
  {
    id: "6",
    name: "Bijou Velours",
    type: "fixe",
    width: 140,
    depth: 82,
    height: 80,
    price: "1099.00",
    comfort: "Confort élégant, assise compacte",
    inStore: false,
    inStock: true,
    onOrder: false,
    mainImage: sofaImage6,
    images: [sofaImage6],
    description: "Petit canapé 2 places au design raffiné, parfait pour les petits espaces.",
    features: ["Velours premium", "Design compact", "Pieds dorés"],
  },
];
